version: "3.7"

services:
  backend:
    container_name: backend
    restart: always
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - ./app/:/usr/src/app/
      - frontend:/usr/src/app/frontend
    ports:
      - 8000:8000
    env_file:
      - env/.env.dev
    command: python3 manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
      - redis
  db:
    container_name: postgres
    restart: always
    image: postgres:12.0-alpine
    environment:
      POSTGRES_USER: hello_django
      POSTGRES_PASSWORD: hello_django
      POSTGRES_DB: hello_django_dev
    ports:
      - 15432:5432
    volumes:
      - ./postgres_data/:/var/lib/postgresql/data
  redis:
    image: redis:5.0.7-alpine
    container_name: redis
    ports:
      - 6379:6379
  celery:
    container_name: celery
    restart: always
    build:
      context: ./app
      dockerfile: Dockerfile
    env_file:
      - env/.env.dev
    volumes:
      - ./app/:/usr/src/app/
      - frontend:/usr/src/app/frontend
    ports: []
    command: celery -A backend worker -l info
    depends_on:
      - db
      - redis
      - backend
  frontend:
    container_name: frontend
    restart: on-failure:1
    build: ./app/frontend
    volumes:
      - ./app/frontend/src:/usr/src/app/frontend/src
      - frontend:/usr/src/app/frontend
    ports:
      - 8080:8080
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
volumes:
  frontend:
