version: "3.7"

services:
  web:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - frontend:/usr/src/app/frontend/
      - ./app/frontend/src:/usr/src/app/frontend/src
      - node_mod:/usr/src/app/frontend/node_modules/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev
  vue:
    build: ./app/frontend
    restart: always
    volumes:
      - frontend:/usr/src/app/frontend/
      - ./app/frontend/src:/usr/src/app/frontend/src
      - node_mod:/usr/src/app/frontend/node_modules/
    ports:
      - 8080:8080
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  postgres_data:
  node_mod:
  frontend:  
