version: "3.7"

services:
  web:
    build:
      context: django
      dockerfile: Dockerfile.prod
    command: gunicorn api.asgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/api/static
      - vue_public:/home/api/public
    expose:
      - 8000
    env_file:
      - env/.env.prod
    depends_on:
      - db
  redis:
    image: redis:5.0.7-alpine
    container_name: redis
    ports:
      - 6379:6379
  celery:
    container_name: celery
    restart: always
    build:
      context: django
      dockerfile: Dockerfile
    env_file:
      - env/.env.prod
    volumes:
      - ./api/:/usr/src/api/
      - vue:/usr/src/api/vue
    ports: []
    command: celery -A api worker -l info
    depends_on:
      - db
      - redis
      - api
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - env/.env.prod.db
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/api/static
      - vue_public:/home/api/public
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  vue_public:
