version: "3.7"

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/static
      - vue_public:/home/app/public
    expose:
      - 8000
    env_file:
      - env/.env.prod
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - env/.env.prod.db
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/static
      - vue_public:/home/app/public
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  vue_public:
