version: "3.7"

services:
  django: &django
    container_name: django
    restart: always
    build:
      context: django
      dockerfile: Dockerfile
    volumes:
      - ./django/:/usr/src/app/
      - webpack-stats:/usr/src/webpack
      - webpack-stats:/opt/project/webpack
    ports:
      - 8000:8000
    env_file:
      - env/.env.dev
    command: python3 manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
      - redis
  db:
    container_name: postgres
    restart: always
    image: postgres:12.0-alpine
    environment:
      POSTGRES_USER: hello_django
      POSTGRES_PASSWORD: hello_django
      POSTGRES_DB: hello_django_dev
    ports:
      - 15432:5432
    volumes:
      - ./postgres_data/:/var/lib/postgresql/data
  redis:
    image: redis:5.0.7-alpine
    container_name: redis
    restart: always
    ports:
      - 6379:6379
  celery:
    <<: *django
    container_name: celery
    ports: [ ]
    command: celery -A app worker -l INFO
    depends_on:
      - db
      - redis
  vue:
    container_name: vue
    restart: on-failure:1
    build: vue
    volumes:
      - ./vue/src:/usr/src/app/src
      - ./vue/package.json:/usr/src/app/package.json
      - webpack-stats:/usr/src/webpack
    ports:
      - 8080:8080
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
volumes:
  webpack-stats:
